### ISSUE TITLE
Wrong behavior for audio and video buttons when browser permissions denied access to devices.

### ISSUE THREAD

**Issue by radukg** [twilio/twilio-video-app-react#417] opened 2021-02-10 17:35 UTC
Seems I can reproduce this issue when the camera access is set to blocked. 
Blocking the camera also sets ToggleAudioButton is stuck on disabled - should this be the case?

![image](https://user-images.githubusercontent.com/78860149/107518656-2a667400-6ba7-11eb-8b67-f8857902bf89.png)

![image](https://user-images.githubusercontent.com/78860149/107518772-4d912380-6ba7-11eb-8c14-f926ec81f334.png)

_Originally posted by @FranBouyakhf in https://github.com/twilio/twilio-video-app-react/issues/377#issuecomment-776720293_

**Comment by timmydoza** [comment] 2021-02-12 18:40
Thanks for the issue @radukg!

Can you please provide more details about the problem that you are seeing? Without detailed steps to reproduce the issue, I won't be able to help out. Can you please give me a detailed list of steps that I can use to reproduce the issue? 

One thing to note here: after you change the camera or microphone permissions, you must reload the page in order for the settings to take effect. Notice in the following gif, that Chrome is displaying a notification that says "To apply your updated settings to this site, reload this page". Are you reloading the page after you apply the settings?

![permission](https://user-images.githubusercontent.com/12685223/102415718-e21b4300-3fb5-11eb-9129-8da2ac08c9c6.gif)

**Comment by timmydoza** [comment] 2021-05-06 00:33
Closing this as it is a duplicate of #428

**Closed by timmydoza** 2021-05-06 00:33 UTC
