### ISSUE TITLE
Audio output devices not switching correctly

### ISSUE THREAD

**Issue by TC-bDelRosario1** [twilio/twilio-video-app-react#184] opened 2020-04-29 06:07 UTC
**Describe the bug**
Audio output devices not switching correctly

**To Reproduce**
1. Connect wired headphones
2. Join Room with another participant
3. Hear other participant on headphones
4. Unplug headphones
5. Hear other participant on built in speakers
6. Plug in headphones
7. Notice participant output comes from speakers not headphones

**Expected behavior**
if headphones are plugged in participant audio plays in headphones otherwise should play on speakers

**Screenshots**

**Environment (please complete the following information):**
 - OS: Mac OSX 10.15.3
 - Browser: Chrome 81
 - App Version: 0.1.0
 - SDK Version: twilio - 3.39.3 | twilio-video - 2.3.0
 - Node.js version: 10.17.0

**Additional context**

**Comment by timmydoza** [comment] 2020-05-05 23:57
Thank you very much for the detailed bug report @TC-bDelRosario1!

I am able to reproduce the issue that you describe. Upon further investigation, it appears to be an issue with Chrome itself. I encounter the same issue on just about any site that plays audio (youtube for example). There's also a related chromium bug report here:

https://bugs.chromium.org/p/chromium/issues/detail?id=1069504&q=headphones&can=2

Since this bug is not part of the twilio-video-app-react codebase, I'll close this issue. Thanks again!

**Closed by timmydoza** 2020-05-05 23:57 UTC
Labels: bug
