### ISSUE TITLE
Android video is garbled.

### ISSUE THREAD

**Issue by datermine** [twilio/twilio-video-app-react#611] opened 2021-11-03 19:50 UTC
**Describe the bug**
The video from this app with no modifications made is showing garbled video from my Android device.

**To Reproduce**
1.  Run + deploy the app
2. Try to connect to a room from an Android device

**Screenshots**
Please see the attached screenshots: One from my phone and the other from a Mac.

**Environment (please complete the following information):**
 - OS: OSX 10.15.6 (19G73) + Android 12 Pixel 3A
 - Browser: Chrome Version 95.0.4638.54 (Official Build) (x86_64)
 - App Version:  0.6.0
 - SDK Version: "twilio-video": "^2.17.1",
 - Node.js version: v16.10.0
 

![from-google-pixel-3a](https://user-images.githubusercontent.com/286251/140182388-2e1718ac-ad3a-4031-b422-45f6a7707658.png)
<img width="1792" alt="Screen Shot 2021-11-03 at 3 44 26 PM" src="https://user-images.githubusercontent.com/286251/140182442-a7d9d259-44f6-4f62-a3a5-7e1c2fd32682.png">

**Comment by nemesisridiculii** [comment] 2021-11-03 20:52
I also have this issue. I'm running android 12 and see this with both firefox and chrome. The video is garbled on ubuntu in both chrome and firefox. (I have tried all 4 combinations with the same results.)

**Comment by olipyskoty** [comment] 2021-11-05 21:09
Hey @datermine thanks for reaching out! 

@zachrattner opened the same issue with the [twilio-video.js team](https://github.com/twilio/twilio-video.js/issues/1627). Looks like this is a known issue, and unfortunately we have to wait for the issue to get fixed in android/chrome 😞 .

The current workaround is to disable hardware encoding in chrome from chrome://flags. Do you mind giving this a try and reporting back if that temporarily fixes the issue?

I do see that @nemesisridiculii mentioned that the same thing is happening in Firefox. @datermine have you tried reproducing this with Firefox? Or is it just Chrome for you?

Thanks and have a great weekend.

**Comment by timmydoza** [comment] 2021-11-24 19:59
Thanks @datermine!

Looks like the root cause of this problem has to do with an Android decoder or Chromium. Doesn't look like a problem with this React application. Since there's a good conversation going on in [this SDK issue](https://github.com/twilio/twilio-video.js/issues/1627), I'm going to close this issue here. This issue can impact users of the SDK, not just users of this app, so I think the SDK repo is the correct location for the issue.

**Closed by timmydoza** 2021-11-24 19:59 UTC
Labels: bug
