### ISSUE TITLE
Error code 20003 from Twilio: Authenticate.

### ISSUE THREAD

**Issue by evgar** [twilio/twilio-video-app-react#246] opened 2020-06-17 21:51 UTC
Error code 20003 from Twilio: Authenticate. While deploying

Steps:

```
$ git clone https://github.com/twilio/twilio-video-app-react
$ cd twilio-video-app-react
$ npm install
$ npm install twilio-cli -g
$ twilio login  
$ twilio plugins:install @twilio-labs/plugin-rtc
$ npm run deploy:twilio-cli
**(Error occured)**
```
![Без названия](https://user-images.githubusercontent.com/14876353/84953896-0c6e6f80-b0fd-11ea-9e85-db2935616d29.png)

**Environment (please complete the following information):**
 - OS: macOS highSierra 10.13.6
 - Browser: Chrome 83.0.4103.97
 - App Version: 0.1.0
 - Node.js version: 12.13.1

**Comment by timmydoza** [comment] 2020-06-18 02:00
Thanks for the issue @evgar!

The error you received indicates that there may be a problem with the credentials used to login to the Twilio CLI. A list of possible causes and possible solutions is available here: https://www.twilio.com/docs/api/errors/20003

If that document doesn't help solve your issue, then you can run the following command to see more verbose logs: `npm run deploy:twilio-cli -- -l debug`
If you post the verbose logs here, we may be able to see what the issue is. 

Thanks!

**Comment by evgar** [comment] 2020-06-18 07:52
Thanks for reply @timmydoza !
**erbose logs**:
```

[DEBUG] Config File: /Users/eugenegarichev/.twilio-cli/config.json
[DEBUG] Using profile: AC4562a70cc5837713cc184e8c89e8f13f
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.46.0, node.js v12.13.1, darwin 17.7.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 401
[DEBUG] response.headers: {"date":"Thu, 18 Jun 2020 07:51:34 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"128","connection":"close","www-authenticate":"Basic realm=\"Twilio API\"","twilio-request-id":"RQ56b6464f794c4cc58095f571139bbaa4","twilio-request-duration":"0.011","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
 » Error code 20003 from Twilio: Authenticate. See https://www.twilio.com/docs/errors/20003 for more info.
[DEBUG] TwilioCliError: Error code 20003 from Twilio: Authenticate. See https://www.twilio.com/docs/errors/20003 for more info.
    at CliRequestClient.request (/Users/eugenegarichev/.twilio-cli/node_modules/@twilio/cli-core/src/services/cli-http-client.js:97:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by timmydoza** [comment] 2020-06-19 02:36
Thanks @evgar!

It seems that the twilio-cli may not be configured correctly. Can you see if another twilio-cli command is successful?

Try running this command as a test. It will display your Twilio usage:
`twilio api:core:usage:records:list`

Does that command succeed, or do you receive a 20003 error? (If you get an error you can run `twilio api:core:usage:records:list -l debug` to get a better error message).

If you are still getting an error then maybe the best thing to do is delete your twilio profile and create a new one. Run `twilio profiles:list` to see all Twilio CLI profiles on your system. Then run `twilio profiles:remove <your_profile_name>` for each profile to delete it. When that is done, you can then run `twilio login` to create a new profile. Creating a new profile will create a new API Key in Twilio Console (seen here: https://www.twilio.com/console/project/api-keys). Be sure not to delete that key, or else the Twilio CLI will not be able to function. 

Since this issue relates to the configuration of the Twilio CLI, and not the React Video App, I'm going to close the issue here. If Twilio CLI problems persist for you, then please create an issue in the [Twilio CLI Github repo](https://github.com/twilio/twilio-cli).

Thanks - and good luck!

**Closed by timmydoza** 2020-06-19 02:36 UTC
Labels: bug
