### ISSUE TITLE
Safari-users get "This webpage is using significant memory (or energy). Closing it may improve the responsiveness of your Mac" 

### ISSUE THREAD

**Issue by liorshk** [twilio/twilio-video-app-react#242] opened 2020-06-14 13:48 UTC
**Describe the bug**
Safari-users get "This webpage is using significant memory (or energy). Closing it may improve the responsiveness of your Mac" warning

**To Reproduce**
Open the page using MacBook Pro

**Expected behavior**
There shouldn't be a warning sign

**Environment (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Safari 13.1.1

**Comment by timmydoza** [comment] 2020-06-18 02:28
Thanks for the info @liorshk!

Our team has not been able to reproduce this issue. 

Some additional information could help us reproduce the issue.  Could you please provide us with the following?

 - A Room SID from a room where this issue is encountered. The Room SID can be found in the Twilio Console, or by accessing `window.twilioRoom.sid` in Safari's JavaScript console. 
 - What model of MacBook you are using
 - Your MacBooks CPU
 - The amount of RAM in your MacBook
 - How frequently this issue is encountered

Additionally, it may be useful to run the Activity Monitor app to see:
 - How much CPU/Memory is Safari consuming
 - If any other apps are consuming significant system resources

The more information you can provide - the better. Thanks so much for your help!!

**Comment by timmydoza** [comment] 2020-07-02 22:16
Closing due to inactivity. Happy to reopen with more information.

**Comment by slauek** [comment] 2021-03-17 13:16
Hi timmydoza
Would it be possible to re-open the topic
1. I am getting this error while browsing www.tradingview.com
2. Macbook Pro 2015 
3. 2.5 GHz Quad-Core Intel Core i7
4. 16 GB 1600 MHz DDR3
5. NVIDIA GeForce GT 750M 2 GB

Issue is almost all the time while I am working with this site. I've tried other browsers, I don't the error but I can see my laptopl trying to fly by using way more fan's and overall being slower.

Additionally
1. Safari consumes approx 30% of GPU power and memmory with the tabs that are corelated with tradingview.

cheers
s

**Comment by timmydoza** [comment] 2021-03-18 00:25
Hi @slauek - I can reopen this issue!

Sorry to hear you are running into this issue. I'll try to dig into it. Can you please provide me with some additional details about the issue?

What version of Safari are you using?
What version of MacOS are you using?
What specific steps can be taken to reproduce the issue in the video app?
What specific steps can be taken to reproduce the issue on tradingview.com?

Thanks!

**Comment by slauek** [comment] 2021-03-18 07:06
Hi @ timmydoza
Any help would be amazing. 

Safari - Version 14.0.3 (16610.4.3.1.7)
macOS Big Sur ver. 11.2.3

Basically, when I open trading-view and my specific chart layout I open two tabs one for each category of instruments I am fallowing. Screenshoot below:
![Screen Shot 2021-03-18 at 8 01 15 AM](https://user-images.githubusercontent.com/72925607/111585819-2dfda400-87c0-11eb-8041-ad5892c236c8.png)

Issues starts when I start switching symbols on the right of the screen but not like right away. Don't know how many times I would switch them so the chart would need to re-load and produce different thing based on the data available for each and every instrument.

I've started to have Safari use one window for one saved layout and Brave for another and then another Brave to have open pages of a trading sites I trade, maximum 2 

best
slauek

**Comment by timmydoza** [comment] 2021-03-26 20:38
Hey @slauek!

Thanks for the additional information. I spent some more time on this, and unfortunately I still wasn't able to reproduce the issue that you describe. 

I did some digging and I found this thread online where many users describe the same issue that you are encountering: https://forums.macrumors.com/threads/how-to-prevent-safari-banner-this-webpage-is-using-significant-energy.2185403/

It sounds like many users are seeing the same warning on many different sites, no matter how powerful their computer might be. 

To me, it sounds like the problem lies with the Safari browser. Based on the comments in that thread, it sounds like Safari is repeatedly displaying the warning, even when it doesn't necessarily make sense for it to do so. 

I can't think of any changes that I can make in this app that would make the warning go away. This app is inevitably going to be more CPU intensive than other websites. Encoding and decoding audio and video streams will consume more system resources than your average website, and there isn't a way around this. Since the problem occurs on other websites, and not just this app, it appears that the problem lies with Safari. Since there isn't anything that I can change in this app to fix it, I'll have to close the issue. 

If you are able to find a solution, please share it here so that other users can find it. Good luck - and please let me know if you have any other questions!

**Closed by timmydoza** 2021-03-26 20:38 UTC
Labels: bug
