### ISSUE TITLE
Token Generation problem after Build

### ISSUE THREAD

**Issue by kvachakhia** [twilio/twilio-video-app-react#525] opened 2021-05-21 05:34 UTC
**Question**
![image](https://user-images.githubusercontent.com/59822053/119087069-8a2ab180-ba17-11eb-93f8-e4b6ca8ff351.png)
/token in this endpoint not sending room_name and user_identity but when I trying in local npm start it's working whats problem after build who can help me

**Comment by timmydoza** [comment] 2021-05-21 23:03
Hi @kvachakhia - thanks for the question!

I see in your screenshot that you are looking in the "Request Headers" section. The `room_name` and `user_identity` won't be found there. If you scroll down to the bottom, you'll find these parameters in the "Request Payload" section:

![image](https://user-images.githubusercontent.com/12685223/119205566-c67d0280-ba55-11eb-91be-0d1a03a6c7e7.png)

Also, if you look in the "Response" pane, you'll see more details about the error you are receiving. If you can share that information with me, I might be able to help out.

I'd be happy to help you get this sorted out, but in order to do so I'll need some more information. Could you please provide me with the following?
- What version of the Video App are you using?
- What versions of Node and NPM are you using?
- What specific steps did you take to get this error?
- Do you see any errors in your Windows console?

The more details, the better I'll be able to help. Thanks!!

**Comment by kvachakhia** [comment] 2021-05-23 09:00
Hi, I use the latest version problem this build version  request payload not showing

**Comment by triple2digital-devteam1** [comment] 2021-05-24 06:21
@kvachakhia did you resolved this, because I'm also facing the same error after run the build

**Comment by kvachakhia** [comment] 2021-05-24 07:22
@triple2digital-devteam1  No didn't fix :(

**Comment by kvachakhia** [comment] 2021-05-24 07:22
@timmydoza   This not have Request Payload........
![image](https://user-images.githubusercontent.com/59822053/119311560-47204680-bc82-11eb-8666-641f503aed13.png)

**Comment by triple2digital-devteam1** [comment] 2021-05-25 04:21
@timmydoza could you please help us with this bug

**Comment by coreymaher** [comment] 2021-05-25 05:02
@kvachakhia Look at the request above that one. It looks like you have a 301 redirect from `.../token` to `.../token/`.
Is your apache config forcing that redirect?

**Comment by kvachakhia** [comment] 2021-05-25 09:32
@triple2digital-devteam1  I use the 0.2.3 version it's working good try it if you don't want new features

**Comment by triple2digital-devteam1** [comment] 2021-05-26 05:48
@kvachakhia I will try this, thank you so much

**Comment by triple2digital-devteam1** [comment] 2021-05-26 09:50
@kvachakhia are you running this node server.js as well?
because now I'm getting this error "Invalid Access Token. Please make sure you are using the correct credentials." after running the build and try to run like this node index.js

**Comment by kvachakhia** [comment] 2021-05-26 10:51
@triple2digital-devteam1  I using PHP  
![image](https://user-images.githubusercontent.com/59822053/119647819-c56f1b00-be31-11eb-9462-f8f02f6ed4e5.png)

**Comment by timmydoza** [comment] 2021-05-26 20:48
Hi @kvachakhia!

I have tried to reproduce the issue from the newest version of the app (0.4.0) and from version 0.2.3 that you mentioned above. I wasn't able to reproduce the problem. With both versions, I was successfully able to connect to a video room.

I think there must be some difference between my code (or environment) and your code (or environment). Have you modified the application code in any way?

Since I can't reproduce the issue that you are experiencing, I will need more information from you in order to help out. Without visibility into your codebase and environment, I won't be able to offer any suggestions. It would help me out if you could please answer these questions:

-What specific steps did you take to get this error? What commands are you running? Please provide as much details as possible.
-What versions of Node and NPM are you using?
-Do you see any errors in your Windows console?
-Are there any errors in the Browser console?
-Have you made any modifications to the codebase?
-If you have made modifications, can you please share the code, or a link to the deployed application?

Thanks for providing additional information! I hope we can get this solved for you soon.

**Comment by timmydoza** [comment] 2021-06-17 22:56
Closing for now. I'm happy to reopen this issue with more information!

**Closed by timmydoza** 2021-06-17 22:56 UTC
Labels: question
