### ISSUE TITLE
Camera still on - even if we click on "turn camera off"

### ISSUE THREAD

**Issue by liorshk** [twilio/twilio-video-app-react#232] opened 2020-06-05 09:07 UTC
**Describe the bug**
When clicking on "turn camera off", it doesn't really turn it off. It only changes the div display.

**To Reproduce**
1. Click on the "Mute Video" button
2. The light near the camera is still on 

**Expected behavior**
We expect, for security purposes, that the camera will not be on when clicking on the "Mute Video" button

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 80
 - App Version: latest
 - SDK Version: 2.5.0
 - Node.js version: 12.14.1

**Comment by timmydoza** [comment] 2020-06-05 15:39
Thanks for the issue @liorshk!

I am unable to reproduce the issue you describe. 

Just wondering - are there any errors that you see in the browser console? I'm wondering if there is some kind of error that is preventing the camera from being turned off. 

Also, have your tried turning off the camera on a different device with a different camera? This would help us figure out if it's a problem with the app, or a problem with the device. 

Lastly does this happen before you join a room, after you join a room, or both?

When the "Mute Video" button is clicked, the app will call `MediaStreamTrack.stop()`. This stops the video stream and releases the camera resource. https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/stop

**Comment by timmydoza** [comment] 2020-06-18 02:30
Closing issue as we cannot reproduce it. Happy to reopen with more information!

**Closed by timmydoza** 2020-06-18 02:30 UTC
Labels: bug
