### ISSUE TITLE
Microphone and Camera are switched on (by default) after disconnection

### ISSUE THREAD

**Issue by Viktar-krauchyk** [twilio/twilio-video-app-react#460] opened 2021-03-18 14:26 UTC
**Describe the bug**
Microphone and Camera mode are reset to 'Start Video' and 'Unmute' after disconnection

**To Reproduce**
1. Enter to the Twillio meeting room
2. Join the meeting
3. Click 'Mute' and 'Stop Video' buttons
4. Disconnect
5. Enter to the same Twillio meeting room
6. Check thу mode of Microphone and Camera

**Expected behavior**
Microphone is switched off
Camera is switched off

**Real behavior**
Microphone is switched ON
Camera is switched ON

**Screenshots**
![mute](https://user-images.githubusercontent.com/79318949/111641271-0a614a80-880e-11eb-9b8e-07cae75b5d09.gif)

**Note**
Bug is not reproduced in Release 0.2.1

**Environment (please complete the following information):**
OS: Windows 10
Browser: Chrome Version 88.0.4324.190 (Official Build) (64-bit)
App Version: 0.2.3
Twilio-video: 2.11.0
Node.js version: 14.15.1

**Comment by timmydoza** [comment] 2021-03-23 01:28
Thanks for the bug report @Viktar-krauchyk!

I can confirm that the behavior you describe is present in the app. I'll create a ticket and add it to our internal backlog.

I consider this to be a feature request and not a bug, so I'll add the appropriate tag to this issue. I don't think it's a bug because this behavior is not caused by existing code working incorrectly. Instead, there is no code to handle the behavior that you wish to see, so we must add it to the app. That said, I still think it would be a nice thing to have in the app, so I'll make a ticket and prioritize it accordingly. 

Thanks again!

**Comment by timmydoza** [comment] 2021-05-06 19:27
Hi @Viktar-krauchyk!

After thinking about this some more, and looking at the behavior of other video apps, I've decided that the won't be adding this feature to this app. Having audio and video tracks enabled whenever the app is loaded appears to be a design choice of other video apps, so we will follow suit in this app as well. 

Thanks again for the suggestion, and please let us know if you have any other questions or suggestions!

**Closed by timmydoza** 2021-05-06 19:27 UTC
Labels: feature
