### ISSUE TITLE
Chat input textbox not centered in Firefox

### ISSUE THREAD

**Issue by coreymaher** [twilio/twilio-video-app-react#498] opened 2021-04-20 21:52 UTC
**Describe the bug**
The text in the chat input textbox is not vertically centered in Firefox like it is in Chrome and Safari.

**To Reproduce**
1. In Firefox, join a video room and open the chat sidebar
2. Notice the "Write a message..." placeholder text is not vertically centered
3. Notice that text that is typed into the textbox is not vertically centered

**Expected behavior**
The text in the chat input textbox is centered

**Screenshots**
Firefox:
<img width="318" alt="Firefox" src="https://user-images.githubusercontent.com/100885/115468260-d4dec100-a200-11eb-896f-4a1023e4a47c.png">

Chrome:
<img width="320" alt="Chrome" src="https://user-images.githubusercontent.com/100885/115468278-da3c0b80-a200-11eb-8b93-1f4fead81d75.png">

Safari:
Looks similar to Chrome

**Environment (please complete the following information):**
 - OS: OSX 10.15.7
 - Browser: Firefox 87.0 and Chrome 89.0.4389.128
 - App Version: v0.3.1
 - SDK Version: 2.13.1
 - Node.js version: 12.20.1

**Additional context**
N/A

**Comment by timmydoza** [comment] 2021-04-23 00:42
Thanks for the issue @coreymaher!

I can reproduce this issue as well. It seems that there are some issues when it comes to applying padding to a `<textarea>` element in firefox. [Searching google](https://www.google.com/search?q=firefox+textarea+padding) seems to bring up a number of relevant issues, including some bugs on bugzilla. 

I'm not sure what the solve here would be, but I can give it some attention. Since this issue only affects the appearance of this element and not its function, this issue will be a little bit of a lower priority for us. I'll add the "good first issue" tag to this issue in case anyone from the community want to submit a PR for it as well.

Thanks again!

**Comment by coreymaher** [comment] 2021-04-23 19:15
Sounds reasonable to me, thanks @timmydoza!

**Comment by timmydoza** [comment] 2021-05-11 16:26
Hey @coreymaher - we got this one fixed and merged into master!

**Closed by timmydoza** 2021-05-11 16:26 UTC
Labels: bug, good first issue
