### ISSUE TITLE
Toggle audio button gets stuck on off, sometimes due to blocked camera permissions

### ISSUE THREAD

**Issue by BenMiriello** [twilio/twilio-video-app-react#377] opened 2020-12-02 16:53 UTC
The ToggleAudioButton is stuck on disabled if video is not permitted or was not on page load, even if video or sound permission is later given.

The ToggleVideoButton seems to have no such issue. If no permission is given at first but is given later, it works as expected. Also settings to audio permissions don't affect ToggleVideoButton behavior.

Is it possible to make the ToggleAudioButton behave the same way as the ToggleVideoButton? About 50% of test users have reported audio is not working and I believe this is why. Many can't get past this issue and are unable to participate in the video room.

How to reproduce (I reproduced in Chrome 87 and Safari 14.0.1 on Mac OS 10.15.7):

1. Load page with mic/speaker/camera permissions on ask/default.
2. Enter name and room name.
3. Don't allow media permissions on initial prompt/s -> both video and audio buttons remain toggled off.
4. Click toggle video button to trigger prompt for camera permission.
5. Give camera permission -> camera is turned on.
6. Click toggle audio button -> nothing happens.

Thanks for looking at this issue.

**Comment by timmydoza** [comment] 2020-12-03 04:41
Thanks for the issue @BenMiriello!

Unfortunately, I'm unable to reproduce your issue. Step #4 isn't working for me.

Unless I grant permissions, both Audio and Video buttons remain disabled for me, and nothing happens when I click them:

![image](https://user-images.githubusercontent.com/12685223/100964994-fb68bd80-34e6-11eb-8ad8-6a6098acc1e4.png)

Just curious, what version of the app are you using when you see this bug?

**Comment by BenMiriello** [comment] 2020-12-04 18:43
Thanks for looking at my issue, Jimmy.

Here is a case where Camera is set to Ask but Microphone and Speaker are set to Allow (I also tested this with all set to Ask/Automatic as per the steps above and it worked the same). I could trigger the camera prompt to turn it on, but audio is stuck on off  ![Camera set to ask - no audio](https://user-images.githubusercontent.com/40286278/101195731-d894f100-362d-11eb-9a85-c4d4f2f2f819.gif)

I was trying to keep it simple in my initial message, but I tried a number of other tests where the toggle media buttons behaved in unexpected ways, either staying stuck on off or with one being affected by change in the other. I'm including just one more demo though since it's relatively simple and possible to replicate. The steps are:
a. Start with all permissions on auto/ask.
b. Enter room and user names and give all permissions. 
c. Switch video to ask and video turns off - that's good
d. Click toggle video button (* 2 times) and it asks for video permission again - that's great
e. Try the same thing with the audio button and it doesn't register the change. Audio indicator keeps showing audio despite changing permission. Unlike the video button, clicking the audio button doesn't trigger asking for permissions again.
![demo 2](https://user-images.githubusercontent.com/40286278/101199959-a8e8e780-3633-11eb-8a2b-2acdf445eb7c.gif)

I understand some of this behavior is unavoidable or expected. I've spend some time trying to fix this issue myself so I understand a bit how the media permissions API is limited and doesn't allow for any perfect solution. Ideally, though, it would be great to have a way to more closely couple each buttons with its own respective media permission state and decouple them from the media permission state of the other button.

The minimum solution I can think of is to just make the toggle audio button trigger its own new request for permission if not granted like the video button does. Though, again, that requires the audio button knowing about the current audio permission state, which sometimes it doesn't.

I hope that clarifies more than it complicates things. Thanks again!

**Comment by timmydoza** [comment] 2020-12-16 22:52
Thanks for the details @BenMiriello!

For your first test - I'm still unable to reproduce it. I tried what you did (with camera set to 'ask' and mic set to 'allow'), and I could not find the issue. When I turn the camera on and off repeatedly, I'm never prompted for permission. 

![cam](https://user-images.githubusercontent.com/12685223/102415405-55708500-3fb5-11eb-9851-19614dc8615a.gif)

Any idea on what I could try differently? I'm curious about how the "Unable to Access Media" error appeared in your first GIF. I didn't see you deny permission anywhere. 


For your second test - I see that the browser is displaying an alert after I change the device settings:
![permission](https://user-images.githubusercontent.com/12685223/102415718-e21b4300-3fb5-11eb-9129-8da2ac08c9c6.gif)

If you restart the browser to apply your new settings, are you finding that the media toggle buttons still exhibit unexpected behavior?

I'm not sure that it would be worth it to try and solve the edge cases that occur when these settings are changed, but not applied to the page via a page refresh. But, if many users are running into issues, then it's worth considering.

**Comment by aaalaniz** [comment] 2021-01-07 16:52
Hey @BenMiriello 

I am closing this issue for now. Please reopen if you need further assistance.

Thank you!

**Closed by aaalaniz** 2021-01-07 16:52 UTC
Labels: bug

**Comment by FranBouyakhf** [comment] 2021-02-10 13:53
Seems I can reproduce this issue when the camera access is set to blocked. 
Blocking the camera also sets ToggleAudioButton is stuck on disabled - should this be the case?

![image](https://user-images.githubusercontent.com/78860149/107518656-2a667400-6ba7-11eb-8b67-f8857902bf89.png)

![image](https://user-images.githubusercontent.com/78860149/107518772-4d912380-6ba7-11eb-8c14-f926ec81f334.png)

**Comment by FranBouyakhf** [comment] 2021-02-10 13:55
> Hey @BenMiriello
> 
> I am closing this issue for now. Please reopen if you need further assistance.
> 
> Thank you!

How do I request for this to be reopened?
