### ISSUE TITLE
Dependency versions of @material-ui/core & @twilio/conversations need to be rolled back

### ISSUE THREAD

**Issue by pBread** [twilio/twilio-video-app-react#552] opened 2021-07-16 19:07 UTC
**Describe the bug**
The dependencies `"@material-ui/core": "^4.9.1"` & `"@twilio/conversations": "^1.1.0"` install the latest versions which have breaking changes. The app throws errors immediately.

The latest version of each package w/out the breaking changes are `"@material-ui/core": "4.11.4"` & `"@twilio/conversations": "1.1.0"`. Package.json should be updated with this versions.

**To Reproduce**
1. Enter into terminal
```
git clone https://github.com/twilio/twilio-video-app-react.git
cd twilio-video-app-react
yarn

```

2. Update the .env file
3. Start app
```
yarn start
```

4. You should see this error on localhost:3000
```
Property 'footerHeight' does not exist on type 'Theme'.  TS2339

    19 | const Main = styled('main')(({ theme }: { theme: Theme }) => ({
    20 |   overflow: 'hidden',
  > 21 |   paddingBottom: `${theme.footerHeight}px`, // Leave some space for the footer
       |                           ^
    22 |   background: 'black',
    23 |   [theme.breakpoints.down('sm')]: {
    24 |     paddingBottom: `${theme.mobileFooterHeight + theme.mobileTopBarHeight}px`, // Leave some space for the mobile header and footer

```

**Environment (please complete the following information):**
 - OS: Catalina 10.15.7
 - App Version: 0.4.1
 - Node.js version: 14.17.1

**Comment by timmydoza** [comment] 2021-07-16 19:53
Hey @pBread - thanks for the issue!

I think this is certainly worth looking into. I'm curious why there are breaking changes in packages that don't bump the major version number. 

I'll look into it, but for your case, I think there's a fix. When you run `yarn install` it ignores the `package-lock.json` file which dictates which specific package versions to install. If you first run the `yarn import` command, it will create a `yarn.lock` file from the `package-lock.json` file. Then, when you run `yarn install`, it should install a stable set of packages. More info here: https://classic.yarnpkg.com/en/docs/cli/import/

Good luck, and please let me know how this works out for you!

**Comment by AkashM398** [comment] 2021-07-18 20:22
Well this exactly the same issue I face right now.. tried the fix which was mentioned by @pBread, but doesn't seem to be working out.. And I use npm for package installation and management, is there any possible fixes available for this?

**Comment by olipyskoty** [comment] 2021-07-19 14:46
Hi @AkashM398! We are sorry to hear that you are having trouble with the app.

Because you mentioned that you use `npm` instead of `yarn`, I went ahead and tried to reproduce the issue and was unable to do so unfortunately. 

Do you mind following the steps below and let me know if you still receive the error? If so, please respond with either a snippet or screenshot of the error.

1. Enter the following commands into your terminal:
```
git clone https://github.com/twilio/twilio-video-app-react.git
cd twilio-video-app-react
npm i
```

2. Update the `.env` file according to the `.env.example` file.
3. Enter `npm start` into the terminal.

Hopefully that should work for you 🤞.

If not, and if you have tried all of the above and everything seems to be configured appropriately, we will need some additional information from you to try to reproduce and find a fix. Please provide us with the following:

**To Reproduce**
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error

**Environment (please complete the following information):**

OS: [e.g. Ubuntu 18.04]
Browser: [e.g. Chrome 80, Firefox 72]
App Version: [e.g. 0.1.0]
SDK Version: [e.g 2.1.0]
Node.js version: [e.g. 12.14.1]


Please let us know if you have any questions in the meantime. Thank you!

**Comment by AkashM398** [comment] 2021-07-19 14:58
I have tried them and later I figured out what happened.. after npm installs all the packages, if I npm audit fix the shown bugs, it messes up few things. I have no idea exactly what they are, but if I build the app without fixing those bugs with npm audit command, it works fine..

To Reproduce
Steps to reproduce the behavior:

`git clone https://github.com/twilio/twilio-video-app-react.git `
`cd twilio-video-app-react `
`npm i`  
`npm audit fix`
`....`
`npm run deploy:twilio-cli`

See error...

Environment:

OS: [e.g. MacOS 11.04]
Browser: [Chrome 91.0]
Node.js version: [e.g. 16.4.2]

**Comment by pBread** [comment] 2021-07-19 23:45
> Well this exactly the same issue I face right now.. tried the fix which was mentioned by @pBread, but doesn't seem to be working out.. And I use npm for package installation and management, is there any possible fixes available for this?

I had a typo in my original. Try replacing your package.json dependencies with this and then install the dependencies.
`"@material-ui/core": "4.11.4, @twilio/conversations": "1.1.0"`.

**Comment by pBread** [comment] 2021-07-19 23:50
> Hey @pBread - thanks for the issue!
> 
> I think this is certainly worth looking into. I'm curious why there are breaking changes in packages that don't bump the major version number.
> 
> I'll look into it, but for your case, I think there's a fix. When you run `yarn install` it ignores the `package-lock.json` file which dictates which specific package versions to install. If you first run the `yarn import` command, it will create a `yarn.lock` file from the `package-lock.json` file. Then, when you run `yarn install`, it should install a stable set of packages. More info here: https://classic.yarnpkg.com/en/docs/cli/import/
> 
> Good luck, and please let me know how this works out for you!

I am using Yarn. The issue is `@material-ui/core` & `@twilio/conversations` changed their structure in their latest versions. For example, in `src/theme.ts` this folder does not exist in the new version of `@material-ui/core`

```
declare module '@material-ui/core/styles/createMuiTheme' {
```

 And similarly to `@twilio/conversations`, the folder `@twilio/conversations/lib/conversation` no longer exists in the most recent version.

The fix is pretty simple. Just update the dependencies so they use the version that was originally inteneded.

**Comment by olipyskoty** [comment] 2021-08-03 22:53
Hi @pBread and @AkashM398! 

We decided to update both Material-UI and Twilio Conversations to their most recent minor versions. This caused me to receive the same errors (and additional warnings) that you both described in your comments above. I went through and made the updates to correct these, but let me know if you run into any more 🙂

In addition, we updated to `npm 7` (read more about that [here](https://github.blog/2021-02-02-npm-7-is-now-generally-available/)) which made a lot of changes to the `package-lock.json` file, but should otherwise go unnoticed.

This [PR](https://github.com/twilio/twilio-video-app-react/pull/568) has been merged into the main branch so please let us know if you have any issues! Thanks again for bringing this to our attention!

**Closed by olipyskoty** 2021-08-03 22:53 UTC
Labels: bug
