### ISSUE TITLE
Flip Camera does not work on iPad when in a room

### ISSUE THREAD

**Issue by pjuchniewicz** [twilio/twilio-video-app-react#161] opened 2020-04-17 12:05 UTC
**Describe the bug**
I was testing the functionality to see how it worked.  On the iPhone while joined to a room, I tested and it worked fine.
When I tested it on an iPad Air 2 while **joined** to a room, the current video (user) stopped / unpublished, but the environment video never starts.  Clicking the button again causes an error, but the video starts back up using the user camera because the last video track received was the environment camera.
When I tested it on an iPad Air 2 while **NOT joined** to a room, it worked fine.

**To Reproduce**
1. Using an iPad, join a room
2. Click on the new Flip Camera button in the menu bar.
3. Participant strip now shows
   - a black area instead of the user camera video.
   - the video off icon displays
4. The environment camera video never displays.  I waited for 30 seconds to see before I did anything else.
5. Clicking on the Flip Camera button again
   - Modal error appears: The [LocalVideoTrack #NN UUID] was unpublished.
   - Overlay appears showing error pointing to:
      - https://github.com/twilio/twilio-video-app-react/blob/master/src/components/MenuBar/FlipCameraButton/FlipCameraButton.tsx
      - Line 28
         - const localTrackPublication = localParticipant?.unpublishTrack(videoTrack!);
6. Close the error modal and overlay.
   - You can see that the video is now displaying again, but it is the user camera video.

**Expected behavior**
On an iPad, it should function the same as it does on an iPhone.  While joined to a room, clicking the button once should replace the user camera video with the environment camera video.

**Environment:**
 - Device: iPad Air 2
 - OS: iPadOS 13.4.1
 - Browser: Safari 13.1
 - App Version: Master Branch as of 4/16/2020

**Additional context**
While doing some more debugging:
- While calling unpublishTrack [line 28], localTrackPublication is populated with a response
- While calling getLocalVideoTrack [line 35], a newTrack is received
- **Issue**: While calling publishTrack [line 36], the promise never completes / publishes the track.  This causes:
   - No displayed video
   - the error on the second click of the flip camera button.

As a test, I modified this to function like the Toggle Video Button does: one click to unpublish the video and one click to switch the camera and publish that video.  That works fine, but it doesn't help for a one-click flip of the camera.

**Comment by timmydoza** [comment] 2020-04-20 21:49
Thanks for the issue @pjuchniewicz! We appreciate that you left us a lot of detail in the issue. This is very helpful.

Unfortunately, I am unable to get my hands on an iPad Air 2 to try and reproduce this issue.  While I find someone at my company that has an iPad Air 2, I'm wondering if you could try something for me. 

You mentioned that the `publishTrack` promise never completes. If you attach a `catch()` handler, what kind of error message do you see?

```
      getLocalVideoTrack(newFacingMode).then(newVideoTrack => {
        localParticipant?.publishTrack(newVideoTrack, { priority: 'low' }).catch(err => console.error('publish track error: ', err));
      });
```

**Comment by timmydoza** [comment] 2020-04-20 21:52
Also, how frequently does this issue occur for you.  100% of the time?

**Comment by timmydoza** [comment] 2020-04-20 22:02
Another idea: it may be possible that the video track hasn't actually been stopped by the time we make the call to `getLocalVideoTrack`. We can wait for the `stopped` event before calling `getLocalVideoTrack`.  Try this:

```
  const toggleFacingMode = useCallback(() => {
    const localTrackPublication = localParticipant?.unpublishTrack(videoTrack!);
    // TODO: remove when SDK implements this event. See: https://issues.corp.twilio.com/browse/JSDK-2592
    localParticipant?.emit('trackUnpublished', localTrackPublication);

    videoTrack!.on('stopped', () => {
      const newFacingMode = facingMode === 'user' ? 'environment' : 'user';

      getLocalVideoTrack(newFacingMode).then(newVideoTrack => {
        localParticipant?.publishTrack(newVideoTrack, { priority: 'low' });
      });
    });

    videoTrack!.stop();
  }, [facingMode, getLocalVideoTrack, localParticipant, videoTrack]);
```

The fact that you got the feature to work when you separated it into two clicks (one for unpublishing, and one for switching cameras and publishing) makes me think that this ^ could do something.

**Comment by pjuchniewicz** [comment] 2020-04-21 18:40
@timmydoza 
> Also, how frequently does this issue occur for you. 100% of the time?

Yes, 100% of the time.

I tested both suggestions and, for both tests, the same thing occurred.
1. Added both a .then and a .catch to the publish() call.
2. Joined a room
3. Clicked on the Flip Camera button.  The video turned off and the no video icon showed on the participant.
4. Waited a few minutes to see if anything would happen, but nothing did.
5. I ended the call and then the console.log in the .catch fired

Here's the version with the .then and .catch added.  The top part is the console messages that occurred after clicking Flip Camera.
![Screen Shot 2020-04-21 at 12 46 23 PM](https://user-images.githubusercontent.com/4603910/79898610-86be9400-83d9-11ea-9e12-b93c6a90b566.png)

Here's the version with the .on('stopped') setup.   The top part is the console messages that occurred after clicking Flip Camera.
![Screen Shot 2020-04-21 at 12 43 34 PM](https://user-images.githubusercontent.com/4603910/79898979-16644280-83da-11ea-8b0e-1e885adfb8a7.png)

As you can see from the console's output, neither the .then or the .catch fire.  The only time they fire is when I then clicked on the end call button, shown below.
![Screen Shot 2020-04-21 at 12 44 16 PM](https://user-images.githubusercontent.com/4603910/79899139-63481900-83da-11ea-9662-6c7bd904ef76.png)


Here is the console when I add an if/else in the Flip Camera code.  It will always use the environment camera since the videoTrack is unpublished every other click and I wanted to see the initial video change.  Nothing is written out on the first click since it is unpublishing / stopping the video and I have no console messages setup for this process.  On the second click, the video is retrieved for the environment camera and published successfully.
![Screen Shot 2020-04-21 at 2 24 23 PM](https://user-images.githubusercontent.com/4603910/79900362-1b29f600-83dc-11ea-9203-4f56dc9e5fb1.png)

**Comment by timmydoza** [comment] 2020-04-22 05:01
Thanks for the info @pjuchniewicz! I really appreciate the amount of detail that you've provided. 

This looks like a legitimate bug.  It seems that the `publishTrack` call is getting stuck on something. 

I have two more ideas for you to try (if you wold be so kind):
  - Add `  logLevel: 'debug'` to the `connectionOptions` object in `src/index.tsx`.  This will print verbose debugging info to the console. There may be more clues in the SDK logs.
  - After you reproduce the issue again, get the Room SID (it's on `window.twilioRoom.sid`) and leave it in a comment here. I can use the Room SID to look up the server-side logs to see what is happening. 

Thanks for all your help on this issue! In the meantime I'm going to get more eyes on the issue since it seems that the bug may even lie in the SDK itself.

**Comment by pjuchniewicz** [comment] 2020-04-22 13:01
Thanks for looking into this @timmydoza!  Here's the info you asked for.

Room SID:  RM46e37f926b177951bf5f81182ea33bd0

I left the console.log messages I had setup in there.

Here is the console after I clicked the Flip Camera button:
![Screen Shot 2020-04-22 at 8 49 44 AM](https://user-images.githubusercontent.com/4603910/79984113-b2438c00-8476-11ea-9e5a-b4e29c423bf5.png)

Unfortunately, I forgot to take a screen capture after I clicked End Call and before I turned off the device. 
 I rejoined the room, clicked Flip Camera, waited a little bit, and then clicked End Call.  Here is console for the messages written out after End Call was clicked.
![Screen Shot 2020-04-22 at 8 50 25 AM](https://user-images.githubusercontent.com/4603910/79984230-e0c16700-8476-11ea-8824-0776737d3ad6.png)

**Comment by timmydoza** [comment] 2020-04-27 04:46
Thanks for all the extra info @pjuchniewicz! It's quite helpful.

This appears to be a known bug with the twilio-video SDK. We have an internal ticket for it. 

There is a workaround. It may work if the local video track is unpublished after the new video track has been acquired. Something like this:
```
localVideoTrack.stop();
newLocalVideoTrack = await createLocalVideoTrack();
room.localParticipant.unpublishTrack(localVideoTrack);
room.localParticipant.publishTrack(newLocalVideoTrack);
```
This way, `unpublishTrack()` and `publishTrack()` both happen with one media negotiation.

I tried this, but there were `track name is duplicated` errors. This can be fixed by publishing the camera track with a name of ``camera-${Date.now()}`` (instead of just `'camera'`). With this change, I had to adjust other parts of the app.

I have [a branch up here](https://github.com/twilio/twilio-video-app-react/compare/fix-ipad-switch-camera) with the whole fix (see [here](https://github.com/twilio/twilio-video-app-react/compare/fix-ipad-switch-camera?expand=1#diff-3c24693e6e7522dd4c04d60c4807afd6R33) for the important part). I still haven't gotten my hands on an iPad Air 2 (can't get into the office with the lockdown) but I'm hoping that you can give it a try. Please let me know how it works for you!

**Comment by pjuchniewicz** [comment] 2020-04-28 10:59
That works @timmydoza!

It's a little slow when the switch actually happens, but it happens without any errors.  I switched back and forth a few times to make sure.

**Comment by timmydoza** [comment] 2020-04-29 05:16
Good to hear @pjuchniewicz!

We created an internal ticket here to add the workaround to the app.

**Comment by timmydoza** [comment] 2020-05-01 19:17
@pjuchniewicz The fix has been merged into master: https://github.com/twilio/twilio-video-app-react/pull/185

Please let me know if you continue to see the issue. Thanks again for all your help in solving this one!

**Closed by timmydoza** 2020-05-01 19:17 UTC
Labels: bug
