### ISSUE TITLE
Switching device orientation causes user to freeze for ~3 seconds

### ISSUE THREAD

**Issue by RusseII** [twilio/twilio-video-app-react#216] opened 2020-05-26 21:58 UTC
**Describe the bug**
Switching the device orientation on safari webview (haven't tested other devices) will cause the user the freeze for about 3 seconds. 

**To Reproduce**
1. Join a room on two devices
2. Make sure one of them is a mobile device
3. Switch the device orientation
4. Observe the user freezing for 3 seconds

**Expected behavior**
The user to not lag when switching device orientation 

**Environment (please complete the following information):**
 - OS: [iPhone]
 - Browser: [Safari Webview (clicked on link through telegram app) ]
 - App Version: [lastest]
 - SDK Version: [2.4]

**Additional context**

**Comment by timmydoza** [comment] 2020-05-27 16:31
Hey @RusseII - thanks for the issue!

I tried this out in iOS Safari and I could not reproduce the issue. Do you see this issue in Safari, or just the Safari Webview when opened with Telegram?

Also, I'm wondering if you could please provide more details about the problem. What does it mean when the user freezes? Does this happen to the user using Safari, or do other participants in the room see something too? Is there a particular video track that freezes, or is it the entire app? 

Thanks again for the info!

**Comment by RusseII** [comment] 2020-05-28 17:48
@timmydoza I'm not sure if it occurs in both - I do not have access to an iOS device that I can do easy testing with.

When encountering the error, I know the user was in a Safari webview. 

By freezing, it happened to both the user, and the other participants (in a small group room) - The audio/video would freeze, almost as if it was "paused" and then resume after about 3 seconds. 

For the other participants, it is just the iOS user's video track that freezes, I'm unsure from the other perspective.

Unfortunately, I don't have a physical iOS device that I can do more testing with to provide better data.  

This isn't a big issue on our side (but obviously if it could be fixed that would be nice)

**Comment by timmydoza** [comment] 2020-06-01 22:31
Thanks for the additional detail @RusseII!

I have an iOS device so I can try it out in a Safari webview. If it's something that can be fixed I'd be happy to work on it, but I'm anticipating that my hands may be tied when dealing with a webview. I'll take a closer look and let you know.

**Comment by timmydoza** [comment] 2020-07-10 19:55
Hey Russell - I tried this out in a webview and I cannot seem to reproduce the issue that you describe. Device orientation seems to happen smoothly for all participants in a room. Since we don't officially support (or test with) Safari WebViews, I'll close this issue, but if you have any additional details about the issue I'd be happy to take a closer look!

**Closed by timmydoza** 2020-07-10 19:55 UTC
Labels: bug, wontfix
