### ISSUE TITLE
Turn off camera and microphone after PreJoinScreens unmount. 

### ISSUE THREAD

**Issue by daire-dev** [twilio/twilio-video-app-react#539] opened 2021-06-15 14:30 UTC
I have cloned this repository and made one small routing change. My app has two routes "/video" and "/" and I am using react-router-dom to navigate between them. "/" renders a simple h1 element and "/video" renders the VideoApp component.

I see that in the PreJoinScreens component there is a useEffect that runs and it's responsible for activating the browser camera and microphone: getAudioAndVideoTracks(). When I navigate back to "/" the camera and microphone stay on. 

I have a half-baked unmount solution and am wondering if there is an easier one. 
I have added the code below, to the VideoApp component. It kind of works, but if I switch between "/" and "/video" pretty quickly it doesn't work. Any help would be greatly appreciated!

```
const { localTracks } = useVideoContext();
  const tracksRef = useRef(localTracks);

  useEffect(() => {
    tracksRef.current = localTracks;
  }, [localTracks]);

  useEffect(() => {
    return () => tracksRef.current.forEach((track) => track.stop());
  }, [])
```

**Comment by timmydoza** [comment] 2021-06-29 22:06
Hi @daire-dev - thanks for the question!

I'm able to reproduce the problem you mention. When I navigate to a `/` path (which just renders a `<h1>` element), the camera light stays on. 

I noticed that there's a difference between 1) using the `Link` component (from react-router-dom) to navigate, and 2) using an anchor element (`<a>`) to navigate. 

When I use something like this:
```
import { Link } from 'react-douter-dom`;
// ...
<Link to="/">Home</Link>
```
the page tranisions to the new route, leaving the camera and microphone on. But when I use an anchor element:

```
<a href="/">Home</a>
```
it's a bit different. Instead of instantly transitioning to the new route, the browser will re-load the whole page at the `/` path. When this happens, the `/` route is loaded without the camera or microphone being on. 

Would using an anchor element work with your use case? Let me know if it doesn't and I can try to think of a good way to stop all tracks when the `VideoApp` component is unmounted.

**Comment by daire-dev** [comment] 2021-07-01 14:37
Hello @timmydoza, thanks for the reply. I also found this to be the most elegant solution myself, using anchor elements instead of the Link component but my boss wanted me to investigate the issue a little further. There are two solutions to work with at least. It seems like something that should be solvable by targeting the window.navigator object directly but I could not seem to find a property along the lines of allTracks or something similar. Ah well, thanks for your help all the same.

**Comment by timmydoza** [comment] 2021-08-17 16:42
Hey @daire-dev - sorry about the delay here, but there is one more solution. 

It's a little less elegant than what's above, but it does seem to work. I added the following code at line 59 of `useLocalTracks.ts`:
```
  const audioTrackRef = useRef<LocalAudioTrack>();
  const videoTrackRef = useRef<LocalVideoTrack>();

  useEffect(() => {
    audioTrackRef.current = audioTrack;
  }, [audioTrack]);

  useEffect(() => {
    videoTrackRef.current = videoTrack;
  }, [videoTrack]);

  useEffect(() => {
    // This cleanup function only runs when the VideoProvider is unmounted
    return () => {
      if (audioTrackRef.current) {
        audioTrackRef.current.stop();
        setAudioTrack(undefined);
      }

      if (videoTrackRef.current) {
        videoTrackRef.current.stop();
        setVideoTrack(undefined);
      }
    };
  }, []); // Refs are used above so that we can keep this dependency array empty, so it only runs on unmount
  ```
  
  This allows us to continue to use the Link component from `react-router-dom`. 
  
  I'll close this issue as it looks like it's resolved. But please let me know if you have any other questions!

**Closed by timmydoza** 2021-08-17 16:42 UTC
Labels: question
