### ISSUE TITLE
Audio input device reloads app to default page

### ISSUE THREAD

**Issue by Orbit-Akhil-Puri** [twilio/twilio-video-app-react#214] opened 2020-05-20 11:31 UTC
![Screenshot_2020-05-20-20-06-11-650_com android chrome](https://user-images.githubusercontent.com/63474776/82460354-af1fd800-9ad6-11ea-862c-8c2e1039d4b4.jpg)
![Screenshot_2020-05-20-20-06-20-042_com android chrome](https://user-images.githubusercontent.com/63474776/82460371-b2b35f00-9ad6-11ea-96ed-775556848907.jpg)

**Describe the bug**
I am not able to choose audio device as Bluetooth speaker from device selector dialog box. Application get stuck and chrome error page apperas.
What I checked is Video.createLocalAudioTrack under getLocalAudioTrack in useLocaltracks creating issues.
It's very urgent for me . Please look into it

**To Reproduce**
1. Go to Device Selector
2. Click on Audio Input List
3. Application hang and chrome error page appears.

**Expected behavior**
I should be able to change my audio device manually if by default audio is not changed.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Browser: Chrome 81

**Additional context**
![IMG_20200521_030010](https://user-images.githubusercontent.com/63474776/82523641-6c97e300-9b4a-11ea-87c5-cd5850aaff9a.jpg)

**Comment by timmydoza** [comment] 2020-05-20 20:52
Thanks for the issue @Orbit-Akhil-Puri!

I'm wondering if you could please provide me with a little more information. It sounds like you have a bluetooth speaker connected, but it isn't showing up in the drop-down menu, is that correct?  Also, do you happen to have a screen shot from the Chrome error page?  Lastly, when you found that `Video.createLocalAudioTrack` was causing the issue, was there an error message that it produced? Are there any other error messages in the browser console?

Thanks for the info! I hope we can get this resolved soon.

**Comment by Orbit-Akhil-Puri** [comment] 2020-05-20 21:21
Hi timmydoza,

Thanks for a quick response. I am getting this issue with both earphone and bluetooth devices on multiple devices having Google Chrome version : 81.04044
Also, I just updated one of my phone to Google Chrome version:83.0 , here I am able to choose wired headset perfectly.

Whenever I tried to choose wired headset option from selected options of dropdown, application gets crash . I am also sharing screenshot for same.
I am not able to see any error in console log as crash window appears.

[Image]

It'll be really helpful if you can help me out with this.


Regards,
Akhil Puri
Sent from Outlook Mobile<https://aka.ms/blhgte>

**Comment by timmydoza** [comment] 2020-05-20 21:25
Thanks @Orbit-Akhil-Puri. Looks like the screenshot didn't come through. Could you please try uploading it again? 

Thanks!

**Comment by Orbit-Akhil-Puri** [comment] 2020-05-20 21:32
Hi timmydoza,

Sharing cropped screenshot. Please let me know if it works.

[Image]

________________________________

**Comment by timmydoza** [comment] 2020-05-21 01:06
Sorry that didn't come through either. I just see the test "[Image]". You may have to upload an image from github.com instead of email.

**Comment by Orbit-Akhil-Puri** [comment] 2020-05-21 04:35
![IMG_20200521_030010](https://user-images.githubusercontent.com/63474776/82523688-93eeb000-9b4a-11ea-85f3-6a51b7536455.jpg)

**Comment by Orbit-Akhil-Puri** [comment] 2020-05-21 04:39
Hi timmydoza,

Just shared screenshot on  github. Please check

Thanks & Regards,
Akhil Puri
________________________________

**Comment by Orbit-Akhil-Puri** [comment] 2020-05-21 15:00
Hi timmydoza,

We are using VP8 and H264 as my preference video codecs while creating room. I am facing multiple issues :
1. Apple Phone and tablet gets heated too much with battery drain out problem. Is it because I am using VP8 codec ios browser. If yes, how can I opt H264 for ios and VP8 for android Or Is it ok to use H264 for all devices.
2. We are providing solution to many prestigious brand customers so what are the parameters I can use for HD quality video .
3. Yesterday, I tried Google chrome beta version- 83.0 and I was able to select and connect Bluetooth headset from device settings but once I try with Chrome version - 80.4 , application get crashed on selecting headset as audio input device . I already shared screenshot in last mail and GitHub account

Thanks & Regards,
Akhil Puri

Thanks & Regards,
Akhil Puri


Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by Orbit-Akhil-Puri** [comment] 2020-05-25 18:10
Hi timmydoza,

I am facing an issue while making a small group call between IOS version 13.4.1 Iphone device and One Plus 6 T device. Audio is not working between participants.

Can you help me to integrate below code in react:

const audioElement = remoteAudioTrack.attach();
divContainer.appendChild(audioElement);

if (/* iOS Safari */) {
  function once(el, event) {
    return new Promise(resolve => {
      el.addEventListener(event, function onEvent() {
        el.removeEventListener(event, onEvent);
        resolve();
      });
    });
  }

  once(audioElement, 'play').then(() => {
    const onPause = once(audioElement, 'pause');
    audioElement.pause();
    return onPause();
  }).then(() => {
    return audioElement.play();
  }).then(() => {
    console.log('Pause/play called!');
  });
}



Thanks & Regards,
Akhil Puri
________________________________

**Comment by timmydoza** [comment] 2020-05-28 00:29
>We are using VP8 and H264 as my preference video codecs while creating room. I am facing multiple issues :
>1. Apple Phone and tablet gets heated too much with battery drain out problem. Is it because I am using VP8 codec ios browser. If yes, how can I opt H264 for ios and VP8 for android Or Is it ok to use H264 for all devices.
>2. We are providing solution to many prestigious brand customers so what are the parameters I can use for HD quality video .
>3. Yesterday, I tried Google chrome beta version- 83.0 and I was able to select and connect Bluetooth headset from device settings but once I try with Chrome version - 80.4 , application get crashed on selecting headset as audio input device . I already shared screenshot in last mail and GitHub account

Thanks for the questions @Orbit-Akhil-Puri!

1 - We have some documentation that talks about the different codecs and how battery life can be optimized on mobile devices: https://www.twilio.com/docs/video/managing-codecs#multi-codec-rooms-using-codec-preferences-for-optimizing-battery-life

The best codec to use can depend on what devices are being used, and whether or not there is hardware support on the devices. Different devices can use different codecs when connected to the same room. It may make sense for one device to send video in one codec, but receive video in another codec. 

2 - This app has already been configured to have good quality. Are you experiencing any issues with the quality? If you are, can you please provide us with some Room SIDs from rooms where you are experiencing issues? Room SIDs can be found in the Twilio Console, or by looking at `twilioRoom.sid` when inside the browser JS console. 

Here is a link that discusses building high quality video applications: https://www.twilio.com/docs/video/tutorials/developing-high-quality-video-applications

3 - The crash that you are experiencing sounds like a browser bug to me. The screenshot you provided is what Chrome displays when the browser crashes. It does not appear to be an error in the app. It sounds like the chrome developers have fixed the issue in the most recent version of Chrome.

**Comment by timmydoza** [comment] 2020-05-28 00:51
>I am facing an issue while making a small group call between IOS version 13.4.1 Iphone device and One Plus 6 T device. Audio is not working between participants.

Thanks for the question @Orbit-Akhil-Puri!

Could you please go into more detail about the audio issue that you are experiencing? I'd just like to make sure that it is the same issue that is discussed in this thread https://github.com/twilio/twilio-video.js/issues/922#issuecomment-633621402

Does the audio fail intermittently, or does it fail 100% of the time?

The issue (https://bugs.webkit.org/show_bug.cgi?id=198545) unfortunately has no good workaround. The problem is that there is no way to detect that an audio track has failed, so it isn't possible to know when to fix the problem. We have found that one of the best things to do is to upgrade iOS. With the newer versions (13.4.1+), we found that this issue occurs much less frequently - perhaps 1 in 50 times. 

We are in touch with the Safari team about the problem, and they are working on a fix.

**Comment by Orbit-Akhil-Puri** [comment] 2020-05-28 18:44
Hi timmydoza,

Thanks for reply.
I already checkes on Ios - 13.5 and its working perfectly.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by Orbit-Akhil-Puri** [comment] 2020-05-28 18:54
Yes, I have checked same and application works perfectly on chrome 84.3 new version.
It's difficult sometimes we need to convince customer to use latest browser version before joining room..

One quick question, we are working an a solution where main participant quality is important and room is having only 2 participants. I am using presentation mode Mostly participants connect thru mobile, What we want to achieve Full HD video on main track . For this, I am publishing track on width : 1920px , height :1080 px and frame rate = 24
Will it work or do we need to change it

Also, Is it good to increase bitSubscriptionVideoBitRate to 5 mb rather than 2.5 mb

Thanks & Regards,
Akhil Puri



Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by Orbit-Akhil-Puri** [comment] 2020-05-28 18:57
Actually, what I have seen in some demos that once I change to group room from small group room with 2 participants then video quality is in FullHd mode. I am not sure whether is that because of network and changing to Group room from small Group room..

Thanks & Regards,
Akhil Puri

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by Orbit-Akhil-Puri** [comment] 2020-05-28 19:04
Hi timmydoza,

I am sharing RoomSid so that you can check how video quality changes once I change RoomType from Group to Small Group

Room Sid - Small Group room
RM1af59438706f8b749f215c431759c67e

Room Sid - Group Room
RM8f439b60e043091d1ac1f42ddc221a00

Thanks & Regards,
Akhil Puri

Sent from Outlook Mobile<https://aka.ms/blhgte>

**Comment by timmydoza** [comment] 2020-06-04 19:34
Hi @Orbit-Akhil-Puri. 

I'd recommend that you look through our [Developing High Quality Video Applications](https://www.twilio.com/docs/video/tutorials/developing-high-quality-video-applications) guide for recommendations of the best settings to use. Below are some of my thoughts for your use case:

- If you require high video quality, then P2P rooms are a good option for rooms that have only 2 participants. If you prefer to use Group Rooms, then I'd recommend Group Rooms instead of Small Group Rooms. Group rooms have a higher Max Downstream Bandwidth per Participant (8 MBPS for Group Rooms, and 4 MBPS for Small Group Rooms. P2P rooms have no limit on Downstream Bandwidth). 

- In devices with restricted CPU or battery life (mobile devices) we recommend setting maxVideoBitrate to a value between 500000 and 2000000 bps per track.  You could try setting it to 5mbps, but it may increase the battery usage of the application. 

Please let me know if you have any other questions. Please check out the above mentioned guide as it is quite comprehensive. I'm happy to keep this discussion going, but I'm going to close this issue because the original issue appears to have been resolved by a Chrome update. 

Also, if you have more general questions about our JS Video SDK, you can leave an issue with the [Twilio Video JS SDK](https://github.com/twilio/twilio-video.js) repository.

**Closed by timmydoza** 2020-06-04 19:34 UTC
Labels: bug
