### ISSUE TITLE
"This site can not ask for your permissions"

### ISSUE THREAD

**Issue by jonra1993** [twilio/twilio-video-app-react#391] opened 2020-12-21 23:07 UTC
**Describe the bug**
After request video and mic permissions on webapp I always get a message that "This site can not ask for your permissions" as a result some devices can neither enter the meeting nor acquire video.

**To Reproduce**
1. Clone master branch
2. Configure credentials 
3. Open Web App on Chrome mobile
4. Accept permissions
4. See the error

**Expected behavior**
I was expecting that after accept permissions, I can show video and listen to the audio.

**Screenshots**
![Screenshot_2020-12-21-13-32-25-084_com android chrome](https://user-images.githubusercontent.com/23468720/102829810-e086bc00-43b5-11eb-9fdf-d809eb885481.jpg)

![Screenshot_2020-12-21-13-31-41-985_com android chrome](https://user-images.githubusercontent.com/23468720/102829789-d664bd80-43b5-11eb-93ac-bfa7048f766a.jpg)

**Environment**
 - OS: Android
 - Browser: Chrome 87.0.4280.101
 - App Version: v0.2.1
 - SDK Version: 2.9.0
 - Node.js version: 14.8.0

**Additional context**
I tested with some devices and it happens in just some Xioami models. I found it happens on  Mi8 lite and Note 4 but in firefox, it works. The problem is presented when using Chrome

**Comment by timmydoza** [comment] 2020-12-28 20:06
Thanks for the issue @jonra1993!

Unfortunately I'm not able to reproduce this issue. I don't currently have access to any Xioami devices. The devices that I do have do not exhibit this issue.

The "This site can't ask for your permission" dialog is not displayed by the video app. It looks like it's displayed by Chrome (or maybe even the OS). 

I did a little bit of research on this. It sounds like the solution is to close or disable any bubbles or overlays. It may be necessary to make adjustments in Settings, because it's possible that an app is displaying an 'invisible' overlay on the page. 

These links discuss problems that aren't 100% related to the error message that you see, but they do contain lots of ideas for fixes and workarounds. I think it may be worth it to try some of them out. Some Xioami users have mentioned that turning off the 'Quick Ball' feature may help:

https://support.google.com/chrome/thread/62124623?hl=en
https://www.androidpolice.com/2019/11/01/psa-chrome-confirmation-buttons-on-android-10-overlay/

Let me know if this helps. Thanks!

**Comment by jonra1993** [comment] 2020-12-31 00:21
Hello, @timmydoza I believe it is a chrome bug because on the same devices it works on Firefox. Thanks for the links I am going to check them these days. Have a happy new year !!

**Comment by timmydoza** [comment] 2020-12-31 22:26
Sounds good @jonra1993!

It may also be worth it to try out this sample app here: https://webrtc.github.io/samples/src/content/getusermedia/gum/

That app simply captures local media and renders it on the page. It may be worth it to see if you encounter the same problem in Chrome with a different application. 

Happy new year! 🎉

**Comment by timmydoza** [comment] 2021-01-15 21:30
Closing this issue as it appears to be related to a Chrome problem and not a problem with this app. Please let me know if you have any related questions and we can reopen!

**Closed by timmydoza** 2021-01-15 21:30 UTC
Labels: bug

**Comment by jonra1993** [comment] 2021-01-16 04:28
> Sounds good @jonra1993!
> 
> It may also be worth it to try out this sample app here: https://webrtc.github.io/samples/src/content/getusermedia/gum/
> 
> That app simply captures local media and renders it on the page. It may be worth it to see if you encounter the same problem in Chrome with a different application.
> 
> Happy new year! 🎉

Thanks, @timmydoza. I tested the link today with the same problematic devices and all of them are able to open links, request video permission and stream video in chrome and firefox android.

**Comment by milinex3** [comment] 2021-07-06 11:16
Thanks a lot for your suggestions @jonra1993 @timmydoza 

But I can resolve this problem with these steps:

1. switch off quick ball by this way: [https://www.sumitcbrty.com/how-to-solve-this-site-cant-ask-for-your-permissionclose-any-bubbles-or-overlays-from-other-apps-then-try-again-on-chrome-on-xiaomi-mi-mobiles/](url)

2. Also I have error 1004 in **bigbluebutton** when I want to turn on my microphone but I resolve it by this way: [https://github.com/bigbluebutton/bigbluebutton/issues/10713](url)

**Comment by megapotz** [comment] 2021-07-23 13:04
In the latest Chrome with QuickBall overlay everything works fine now, in January I was getting getUsermedia promise never resolved. Can anyone confirm this thing is generally fixed, or is it just my phone's own behaviour?

**Comment by NanduWasTaken** [comment] 2022-02-05 08:50
Itz the problem with the chrome permission @jonra1993 
Watch this [video](https://youtu.be/xsNZnTFu0r8)
Hope it helps😀

**Comment by NanduWasTaken** [comment] 2022-02-05 08:52
One more detail If chrome doest have the video permission how the heck 
Can chrome give the site the permission 
Hope it makes sence
