### ISSUE TITLE
Video was freezing after display/hiding in mobile safari

### ISSUE THREAD

**Issue by AndreyPatseiko** [twilio/twilio-video-app-react#395] opened 2021-01-05 11:04 UTC
**Describe the bug**
I used one local video track in couple places and displayed/hided it at some conditions. After hiding video element in one place the other video just frozen.  Doesn't matter how hide element by attributes or with classes. 
Get this behavior only real mobile device (IPhone X) and safari.  

**To Reproduce**
Added code for show/hide couple local video elements.
Or you can just update src/components/PreJoinScreen/DeviceSelectionScreen/**DeviceSelectionScreen**.tsx element in your repository to:

    export default function DeviceSelectionScreen({ name, roomName, setStep }: DeviceSelectionScreenProps) {
    const classes = useStyles();
    const { getToken, isFetching } = useAppState();
    const { connect, isAcquiringLocalTracks, isConnecting } = useVideoContext();
    const disableButtons = isFetching || isAcquiringLocalTracks || isConnecting;
    const [showFirst, setShowFirst] = useState(true) <----------------------------
    const [showSecond, setShowSecond] = useState(true) <--------------------------

    const handleJoin = () => {
      getToken(name, roomName).then(token => connect(token));
    };

    return (
    <>
      <Typography variant="h5" className={classes.gutterBottom}>
        Join {roomName}
      </Typography>

      <Grid container justify="center">
        <Grid item md={7} sm={12} xs={12}>

          {showFirst ? <div className={classes.localPreviewContainer}> <---------SHOW\HIDE VIDEO
            <LocalVideoPreview identity={name} />
          </div> : null
          }

          {showSecond ?
            <div className={classes.localPreviewContainer}> <---------SHOW\HIDE VIDEO
              <LocalVideoPreview identity={name} />
            </div> : null
          }

          <div className={classes.mobileButtonBar}>
          <button onClick={() => {setShowFirst(!showFirst)}}>hide first</button> <-----------TRIGGER BTN
          <button onClick={() => {setShowSecond(!showSecond)}}>hide second</button> <----------TRIGGER BTN
            <Hidden mdUp>
            ........

Launched application in local machine with https protocol. Changed dev script to -> "dev": "**HTTPS=true** react-scripts start". 
Play with showing/hiding video elements.
In Safari debug console I got message 

      2021-01-06T11:53:50.779Z – "warn" – "[LocalVideoTrack #1: 0ed2b25b-ae7a-4660-8729-d2b6758aca50]" – "Unintentionally paused:"

**Expected behavior**
Video mustn't stop!

**Environment:**
 - OS: IOS 12.3.1
 - Browser: mobile Safari 12
 - App Version: 0.2.1
 - Node.js version: v14.8.0

**Comment by timmydoza** [comment] 2021-01-15 21:18
Hey @AndreyPatseiko - thanks for the issue!

I tried out your code snippet and I was unable to reproduce the issue that you mentioned. I can click both hide buttons to make the LocalVideoPreview appear and disappear, and the video is never paused or frozen. I notice that you are using a much older version of iOS (version iOS 12.3 was released 19 months ago). I'm using version 14.3 on my iPhone. Unfortunately, I'm unable to downgrade my version of iOS to try and reproduce the issue under similar conditions. 

Can you please try upgrading your version of iOS to see if the issue still persists with the newer version?

I'm going to close this issue as the bug you mentioned isn't present in the version of the codebase as it exists on the `master` branch. Additionally, the warning that you shared is not emitted by this app - it is emitted by the [twilio-video.js](https://github.com/twilio/twilio-video.js) library. So if the issue persists, it may be worth it to open an issue in that library. Please do let me know if you have any additional questions!

**Closed by timmydoza** 2021-01-15 21:18 UTC
Labels: bug
