### ISSUE TITLE
raise the `ELIFECYCLE` error randomly

### ISSUE THREAD

**Issue by vincecao** [twilio/twilio-video-app-react#106] opened 2020-03-25 08:49 UTC
**Describe the bug**
When I do `npm run deploy:twilio-cli -- --override` serval times, it will raise the `ELIFECYCLE` error.

have check typescript in 3.7.5 for preventing `participants` typescript error, can successfully. build in local env

**To Reproduce**
1. `npm run deploy:twilio-cli`
2. several `npm run deploy:twilio-cli -- --override`
3. `ELIFECYCLE` error

**Environment (please complete the following information):**
 - OS: Mac & Windows
 - Browser: NA
 - App Version: 0.1.0
 - SDK Version: 3.39.3
 - Node.js version: v13.6.0

**Additional context**
Error in console:
```
» twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the twilio-video-app-react@0.1.0 deploy:twilio-cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vincec/.npm/_logs/2020-03-25T08_39_25_767Z-debug.log
```

Full Error in log
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/13.6.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy:twilio-cli'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v13.6.0
4 verbose run-script [
4 verbose run-script   'predeploy:twilio-cli',
4 verbose run-script   'deploy:twilio-cli',
4 verbose run-script   'postdeploy:twilio-cli'
4 verbose run-script ]
5 info lifecycle twilio-video-app-react@0.1.0~predeploy:twilio-cli: twilio-video-app-react@0.1.0
6 info lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: twilio-video-app-react@0.1.0
7 verbose lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: unsafe-perm in lifecycle true
8 verbose lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/vincec/xxx/node_modules/.bin:/Users/vincec/.yarn/bin:/Users/vincec/.config/yarn/global/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/vincec/.yarn/bin:/Users/vincec/.config/yarn/global/node_modules/.bin:/Users/vincec/Library/Android/sdk/emulator:/Users/vincec/Library/Android/sdk/tools:/Users/vincec/Library/Android/sdk/tools/bin:/Users/vincec/Library/Android/sdk/platform-tools:/Users/vincec/Library/Android/sdk/emulator:/Users/vincec/Library/Android/sdk/tools:/Users/vincec/Library/Android/sdk/tools/bin:/Users/vincec/Library/Android/sdk/platform-tools
9 verbose lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: CWD: /Users/vincec/xxx
10 silly lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build'
10 silly lifecycle ]
11 silly lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: Returned: code: 1  signal: null
12 info lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: Failed to exec deploy:twilio-cli script
13 verbose stack Error: twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid twilio-video-app-react@0.1.0
15 verbose cwd /Users/vincec/xxx
16 verbose Darwin 19.3.0
17 verbose argv "/usr/local/Cellar/node/13.6.0/bin/node" "/usr/local/bin/npm" "run" "deploy:twilio-cli"
18 verbose node v13.6.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build`
22 error Exit status 1
23 error Failed at the twilio-video-app-react@0.1.0 deploy:twilio-cli script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by timmydoza** [comment] 2020-03-26 22:36
Thanks for the detailed issue @vincecao!

Unfortunately I can't seem to reproduce the issue on my local machine.  
Some additional questions for you:
- How many times do you run `npm run deploy:twilio-cli -- --override` before the error occurs?
- How frequently do you run `npm run deploy:twilio-cli -- --override`?
- Does this happen in both MacOS and Windows for you?
- How much RAM and free disk space does your system have?

It's a strange error, and it's hard to tell exactly what is happening. Have you checked google or stackoverflow for info related to the `ELIFECYCLE ` error code?

**Comment by patrickomatik** [comment] 2020-03-27 09:07
I have exactly the same issue, identical logs. 
This is my first install (and first attempt at using Twilio -- less than awesome to fail at first hurdle) - onto Ubuntu 18.04 8GB RAM 23GB free disk space.

**Comment by patrickomatik** [comment] 2020-03-27 09:09
DDGing ELIFECYCLE - first hit gives me https://stackoverflow.com/questions/30744964/what-does-the-elifecycle-node-js-error-mean

"It's basically saying it fails to spawn your process not due to permission but to an error in your script."

**Comment by timmydoza** [comment] 2020-03-27 23:24
Thanks for the information @patrickomatik and @vincecao!

I suspect that you are both encountering a known issue that has been discussed here: https://github.com/twilio-labs/plugin-rtc/issues/16

If you are interested, you can enable logs to see if you getting the same error message: `npm run deploy:twilio-cli -- --override -l debug`.

We have identified the root cause of the issue, and the Serverless team here at Twilio will have a fix out in the next few days. In the meantime, there is a workaround to get things working again.

First, upgrade the Twilio CLI plugin: `twilio plugins:update`.
Then, run `twilio rtc:apps:video:delete`.  The app that was deployed is likely in a corrupt state, and running this command will remove it. 
Once the app is deleted, try running `npm run deploy:twilio-cli` again. It should deploy without problems. 

Good luck, and please let me know if you continue to see problems.  Thanks!

**Comment by timmydoza** [comment] 2020-03-30 22:57
This issue has now been fixed by Twilio's Serverless team, so I'll close the issue.

**Closed by timmydoza** 2020-03-30 22:57 UTC
Labels: bug

**Comment by gomobishop** [comment] 2020-06-01 00:58
i have the  same  issue

**Comment by timmydoza** [comment] 2020-06-01 22:39
Hi @gomobishop - We would be happy to help out! Can you please create a new issue and fill out the issue template with all of the relevant details? In order to help, we will need to know more about the exact problem that you face. Thanks!

**Comment by chai2** [comment] 2020-07-18 20:17
+1. Having same issue. Is there a workaround for this? Just signed up for a new twilio account and following the documentation lead me to this error.

**Comment by leepowers** [comment] 2020-09-18 18:42
I'm also having the same issue.

The error message triggering seems to be 


Details as follows:

**Steps to Reproduce**

```
git clone https://github.com/twilio/twilio-video-app-react
cd twilio-video-app-react
npm install
npm install twilio-cli -g
# Account SID and Auth Token from: https://www.twilio.com/console/
twilio login
twilio plugins:install @twilio-labs/plugin-rtc
npm run deploy:twilio-cli
```

^ Bug occurs on deploy last step with note:

***`» twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio-labs/plugin-rtc"`***

**Error Output**

```
npm run deploy:twilio-cli -l debug

> twilio-video-app-react@0.1.0 deploy:twilio-cli /Users/leepowers/work/takeda/video-app/twilio-video-app-react
> cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build "debug"


> twilio-video-app-react@0.1.0 build /Users/leepowers/work/takeda/video-app/twilio-video-app-react
> node ./scripts/build.js

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  271.8 KB  build/static/js/2.4d5918e3.chunk.js
  15.15 KB  build/static/js/main.431b0198.chunk.js
  787 B     build/static/js/runtime-main.d9f235a9.js

 ›   Error: EEXIT: 1
 ›   Code: EEXIT
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the twilio-video-app-react@0.1.0 deploy:twilio-cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

```

**Debug Log File**

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/14.10.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy:twilio-cli'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.10.0
4 verbose run-script [
4 verbose run-script   'predeploy:twilio-cli',
4 verbose run-script   'deploy:twilio-cli',
4 verbose run-script   'postdeploy:twilio-cli'
4 verbose run-script ]
5 info lifecycle twilio-video-app-react@0.1.0~predeploy:twilio-cli: twilio-video-app-react@0.1.0
6 info lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: twilio-video-app-react@0.1.0
7 verbose lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: unsafe-perm in lifecycle true
8 verbose lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/leepowers/work/takeda/video-app/twilio-video-app-react/node_modules/.bin:/Applications/dart-sass:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: CWD: /Users/leepowers/work/takeda/video-app/twilio-video-app-react
10 silly lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build'
10 silly lifecycle ]
11 silly lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: Returned: code: 1  signal: null
12 info lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: Failed to exec deploy:twilio-cli script
13 verbose stack Error: twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1047:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid twilio-video-app-react@0.1.0
15 verbose cwd /Users/leepowers/work/takeda/video-app/twilio-video-app-react
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/Cellar/node/14.10.0/bin/node" "/usr/local/bin/npm" "run" "deploy:twilio-cli"
18 verbose node v14.10.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build`
22 error Exit status 1
23 error Failed at the twilio-video-app-react@0.1.0 deploy:twilio-cli script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
