### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.enumerateDevices')

### ISSUE THREAD

**Issue by ravara** [twilio/twilio-video-app-react#225] opened 2020-06-03 16:46 UTC
When loading the the app locally or via twilio serverless, you will encounter this error on Chrome for iOS. Tested on an iPhone 11.

![File](https://user-images.githubusercontent.com/65049762/83664528-fc905080-a57e-11ea-83c0-b64f15443d31.jpg)

**Comment by ravara** [comment] 2020-06-03 20:58
Ah, I see webRTC isn't supported by Chrome for iOS. Any plans for another approach here?

**Comment by everbslab** [comment] 2020-06-04 12:53
I perfomed a workaround to alert user to use Safari on iOS:

`// iOS and Chrome browser incompatible due to Chrome on iOS doesn't support WebRTC
// refer to: https://www.npmjs.com/package/twilio-video
if (isIOS && (isChrome || isChromium)) {
  alert('This browser is not supported. Please use Safari browser.');`

**Comment by aaalaniz** [comment] 2020-06-04 15:45
Duplicate of #217

**Closed** 2020-06-04 15:45 UTC
Labels: bug

**Comment by timmydoza** [comment] 2020-06-04 18:22
To provide some guidance - the twilio-video SDK does have an `isSupported` boolean that can be used to alert users when they are using an unsupported browser:

https://media.twiliocdn.com/sdk/js/video/releases/2.0.0/docs/module-twilio-video.html

It can be used like this:

```
import Video from 'twilio-video';

if (!Video.isSupported) {
  // alert user that browser is not supported
}
```

Next week we will be adding something similar to this app.  It will show a useful error message when the browser is not supported (instead of crashing).

**Comment by aevaldas** [comment] 2020-06-09 08:11
iPhone XS
iOS 13.4.1
Safari 13

twilio-video-app-react@0.1.0

![IMG_8875](https://user-images.githubusercontent.com/38099310/84122104-9a34c580-aa40-11ea-94bf-d94c91c8c835.PNG)

According to https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices I see that enumerateDevices are supported since Safari 11:
![image](https://user-images.githubusercontent.com/38099310/84122856-bd13a980-aa41-11ea-8453-bb09195c0e58.png)
