### ISSUE TITLE
Video settings are reset to default value after disconnection for the first time.

### ISSUE THREAD

**Issue by Viktar-krauchyk** [twilio/twilio-video-app-react#440] opened 2021-03-01 15:21 UTC
**Describe the bug**
Video settings are not saved after disconnection for the first time.

**To Reproduce**
1. User has more than one camera
2. Open Twillio page in incognito mode (First camera is selected by default)
3. Change Video Input to the Second camera and Save
3. Join the room.
4. Leave the room
5. Check which camera is selected

**Expected behavior**
Second camera is selected

**Real behavior**
First camera is selected

**Screenshots**
![Second camera](https://user-images.githubusercontent.com/79318949/109517242-17fe9c80-7aba-11eb-95c9-1a86b2ced97b.gif)

**Environment (please complete the following information):**
OS: Windows 10
Browser: Chrome Version 88.0.4324.190 (Official Build) (64-bit)
App Version: 0.2.3
Twilio-video: 2.11.0
Node.js version: 14.15.1

**Comment by timmydoza** [comment] 2021-03-03 21:55
Thanks for the detailed bug report @Viktar-krauchyk!

I can confirm that this bug exists. I believe that it has the same root cause as this other github issue: #425

There is already a ticket in the backlog to fix the root cause of this issue.

Thanks again for the reports!

**Comment by timmydoza** [comment] 2021-05-12 00:08
Hi @Viktar-krauchyk - the fix for this has been merged into the master branch. Thanks again for bringing it to our attention!

**Closed by timmydoza** 2021-05-12 00:08 UTC
Labels: bug
