### ISSUE TITLE
Newly created deployments have expired passcodes on creation

### ISSUE THREAD

**Issue by Shagans982** [twilio/twilio-video-app-react#515] opened 2021-05-11 15:10 UTC
Im aware passcodes only last a week and then you need to create a new one but every new deployment I create tells me my passcode expires a day in the past, no the future so I can't access any of the portals. Just tells me passcode expired. This was created today, May 11th. 

Expires: Mon May 10 2021 10:07:55 GMT-0500

**Comment by Shagans982** [comment] 2021-05-12 14:26
@timmydoza any updates here?

**Comment by olipyskoty** [comment] 2021-05-12 17:35
Hi @Shagans982, thanks for reaching out!

Unfortunately, we are not entirely sure what could be causing this issue, but there are a couple of things we could try! 

We believe that the passcode expiration date is based on your system's date and time. In attempt to reproduce this issue, I tried setting my system's date and time back one week from today, did a quick deploy, and saw that my passcode was set to expire appropriately:
`Expires: Wed May 12 2021 11:20:59 GMT-0400`.

Do you mind verifying that the date and time for `node` and your system are current by running the following commands in your terminal? Please let us know if the outputs differ from the current date and time.

- `date`
- `node -e "console.log(Date())"`

In addition, if you have altered any code in the `plugin-rtc`, issues may arise. Could you please confirm that this [line](https://github.com/twilio-labs/plugin-rtc/blob/master/src/constants.js#L2) from `src/constants.js`hasn't been changed?
`module.exports.EXPIRY_PERIOD = 1000 * 60 * 60 * 24 * 7; // One week`

Finally, if you have tried all of the above and everything seems to be configured appropriately, we will need some additional information from you to try to reproduce and find a fix. Please provide us with the following:

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Browser: [e.g. Chrome 80, Firefox 72]
 - App Version: [e.g. 0.1.0]
 - SDK Version: [e.g 2.1.0]
 - Node.js version: [e.g. 12.14.1]

Please let us know if you have any questions in the meantime. Thank you!

**Comment by Shagans982** [comment] 2021-05-12 18:12
Dates appear to be fine. I don't have a constants.js, only a typescript version. See photo of contents. 
![Screen Shot 2021-05-12 at 1 11 24 PM](https://user-images.githubusercontent.com/753760/118023872-aa75b480-b323-11eb-9968-f2da68683477.png)
![Screen Shot 2021-05-12 at 1 11 05 PM](https://user-images.githubusercontent.com/753760/118023905-af3a6880-b323-11eb-8305-849691d807d8.png)

**Comment by olipyskoty** [comment] 2021-05-12 21:32
Hi again, @Shagans982!

Do you mind sending us the exact steps you took to experience this issue, including a screenshot of your terminal? Without this information it is difficult for us to pinpoint where this may be coming from. 

One thing we have noticed in the past is that if you have quick-deployed a video app, and try to deploy a new one using
`npm run deploy:twilio-cli`, a new passcode will not be generated so the expiration date will not update either. 

To redeploy the app with a fresh passcode and expiration date, you'll need to run `npm run deploy:twilio-cli -- --override`. Another option is to delete the deployed app using `twilio rtc:apps:video:delete`, and then run `npm run deploy:twilio-cli`  again to deploy a brand new one.

Thanks again!

**Comment by Shagans982** [comment] 2021-05-12 21:42
Im actually leaving out of town currently. Ive had this working for a long time (close to a year) and all of a sudden it started doing this. Ive updated to the latest code, installed dependencies (via NPM and Yarn), authenticated with my Twilio info and deployed. Ive blown away my entire CLI and reinstalled and am still getting the same result.

**Comment by Shagans982** [comment] 2021-05-18 15:46
I just had a co-worker perform a fresh install following your guide and they  got the same. A passcode that expires on May 10th, 2021 ie already expired.

**Comment by timmydoza** [comment] 2021-05-19 15:30
Hi @Shagans982 - sorry to hear that you have having trouble with our quick deploy demo.

I have tried to deploy a fresh install of the app, and I could not reproduce the problem that you are experiencing. When I deployed the app, the expiration was correctly set for May 26, one week from today.

I think that there might be a problem with your specific environment. Unfortunately, we won't be able to help you out unless you can provide us with detailed information with respect to 1) the exact steps you are taking, 2) the versions of the software you are using, and 3) the console output that you see after you try to deploy an app. Without any information, we won't have the ability to solve the problem, and we'll have to close the issue. 

Can you please provide us with a detailed list of steps that we can take to reproduce the issue? The more details that you can provide, the better. Please share what you see in the console after you try and deploy an app. 
 
 Additionally, can you please provide us with the output of the following commands?
`npm -v`
`node -v`
`twilio -v`
`twilio plugins`
`twilio rtc:apps:video:view`

Lastly, when your co-worker performed a fresh install and deployment, did they use a new Twilio account SID? Or was it the same account SID that you were using? Your account SID used for deployment can be found with `twilio profiles:list`.

Thanks for helping us solve this issue by providing this information! We look forward to getting this issue solved for you, but we can't do it without detailed information about your environment. Thanks for understanding!

**Comment by olipyskoty** [comment] 2021-06-07 20:07
Closing due to inactivity. Happy to reopen with more information!

**Closed by olipyskoty** 2021-06-07 20:07 UTC
