### ISSUE TITLE
Microphone input does not work in Safari

### ISSUE THREAD

**Issue by nalinbhardwaj** [twilio/twilio-video-app-react#322] opened 2020-10-01 21:21 UTC
**Describe the bug**
Microphone input does not work when using Safari since the [`62b5ce6`](https://github.com/twilio/twilio-video-app-react/commit/62b5ce6ab47fd421e2e877d639c86f3312a95351) commit. Granting microphone permission does not activate on the browser's microphone symbol either. Repeatedly muting and unmuting shows these console logs: "`[Warning] 2020-10-01 – "21:10:05.106Z" – "|" – "WARN" – "in" – "[LocalAudioTrack #3: e7157454-ad7e-4aad-ab18-83eab8f46af9]:" – "Got a silent audio MediaStreamTrack. Stopping all MediaStreamTracks and calling getUserMedia again. This is retry #2." (2.d54d144d.chunk.js, line 2)`"

**To Reproduce**
1. Deploy commit 62b5ce6 and enter a room.
2. Microphone input is not detected. Repeatedly mute and unmute to see the other console log.

**Expected behavior**
Microphone input is detected and transmitted.

**Environment (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser: Safari Version 13.1 (15609.1.20.111.8)
 - App Version: commit `62b5ce6`
 - Node.js version: v12.18.0

**Additional context**

This bug seems related to https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md#mobile-safari-participants-on-ios-1301-sometimes-fail-to-send-audio but I'm not sure what broke after the latest change.

**Comment by timmydoza** [comment] 2020-10-07 17:04
Thanks for the question @nalinbhardwaj!

Unfortunately, I couldn't reproduce this issue. I don't have the same version of Safari installed as you - I'm running Safari version 14.0 on macOS 10.15.7.

What audio device is the app trying to use? I'm wondering if you are seeing the `Got a silent audio MediaStreamTrack` warning because your audio input device is actually producing a silent stream. Does your audio input device work on other websites/programs? 

Also, in the video app, can you select a different audio device to use by going to Settings > Audio and Video Settings?

**Comment by nalinbhardwaj** [comment] 2020-10-07 18:33
@timmydoza  I can only reproduce this behaviour in Safari 13.1 (updating to 14 resolved it for me too). And yeah, audio input works just fine in other apps (in fact, I was deploying a previous commit of the react app at the same time and it was working for that as well). I'm using the default MacBook Pro Microphone. Trying another audio device from Settings did not fix this either.

**Comment by timmydoza** [comment] 2020-10-21 21:45
I'm wondering if it has something to do with this: https://github.com/versatica/mediasoup-client/issues/101#issuecomment-567559926

If you enable "WebRTC Unified Plan" in the developer menu of Safari 13.1, does the audio work again? Let me know how that works out for you!

In the meantime I'll close this issue. The problem seems to be with that specific version of Safari, and not with this app. 

Thanks!

**Closed by timmydoza** 2020-10-21 21:45 UTC
Labels: bug
